### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by mjknght** [mnadel/freddiebear#2]
This looks great! I’m having trouble getting it working, however. Having installed the workflow from the latest installation, the debugger shows:

```
Freddiebear[Script Filter] Script with argv '(null)' finished
[13:32:51.566] ERROR: Freddiebear[Script Filter] Code 127: zsh:1: command not found: freddiebear
```

Perhaps I have to install something else separately? Thanks in advance for any steers.

**Comment by mnadel** [comment]
If `freddiebear` isn't in your path, you can specify its location here:

<img width="953" alt="image" src="https://github.com/user-attachments/assets/3caf34a2-74dc-44f4-9813-daf60bbe7a0f">

**Comment by mnadel** [comment]
Sorry! The most recent version moved this to the workflow config, did you add a value there?

<img width="1225" alt="image" src="https://github.com/user-attachments/assets/9753b33d-69c7-45ef-a47c-65ed83b2a74b">

**Comment by mjknght** [comment]
Sorry, late response! Forgive the silly question, but I take it this means I need to install a binary separate from downloading and adding the Alfred Workflow? Thanks in advance.

**Comment by mnadel** [comment]
Alright, v1.9.2 now has a `fbinstall` command to install the binary. If you update to this version, then run that keyword, you should be good. Let me know how it goes.

**Comment by mjknght** [comment]
Hello! Sorry for a late response; just back from a couple of weeks away.

I’ve updated and tried this, but get the following:

```
[10:24:05.973] ERROR: Freddiebear[Run Script] Mon Aug 26 10:24:05 +08 2024 freddiebear.arm64.gz icon.png info.plist downloading ver=1.9.2 arch=arm64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0    131      0 --:--:-- --:--:-- --:--:--   132
uncompressing
gzip: freddiebear.arm64.gz: not in gzip format
[10:24:05.987] Freddiebear[Run Script] Processing complete
[10:24:05.988] Freddiebear[Run Script] Passing output 'error
' to Conditional
[10:24:05.989] Freddiebear[Conditional] Processing complete
[10:24:05.990] Freddiebear[Conditional] Passing output 'error
' to Post Notification
```

Is the problem on my end?

**Comment by mnadel** [comment]
If you update to the latest (1.9.3) this should be fixed, sorry!

**Comment by mjknght** [comment]
Hi, sorry, I should have specified that this is the message I get when running `fbinstall` in 1.9.3.

**Comment by mnadel** [comment]
Just to confirm -- in the log output you posted, it's showing v1.9.2; did you upgrade after capturing the above and are still seeing the issue?

**Comment by mjknght** [comment]
Oh, I had not spotted that! When I download the workflow from the 1.9.3 release and open it, it is 1.9.2 that I see. Is the wrong version included in the release? Perhaps that’s why it is not working. Thanks again, looking forward to giving the workflow a spin when I finally crack this!

**Comment by mjknght** [comment]
Hi there! Just to be clear, having checked again – after I download 1.9.3, I still see 1.9.2 as the version. I am wondering whether that’s the version included in the release by mistake. Thanks again in advance!

**Comment by mnadel** [comment]
Apologies, just seeing this now :( I'll take a look & get back to you soon!

**Comment by mnadel** [comment]
The download script uses the workflow version variable that Alfred set, so there _shouldn't_ be a mismatch.

In the meantime you can download the binary here and place it in the workflow folder. Opening it _should_ uncompress it into a binary named `freddiebear`.

Apple Silicon: https://github.com/mnadel/freddiebear/releases/download/1.9.3/freddiebear.arm64.gz

Intel: https://github.com/mnadel/freddiebear/releases/download/1.9.3/freddiebear.x86_64.gz

**Comment by mjknght** [comment]
Thank you for your help so far! I have downloaded this binary (for Apple silicon in my case) to the workflow folder and have tried to run `fbinstall`. This is what I get:

```
[17:02:12.742] Freddiebear[Keyword] Processing complete
[17:02:12.747] Freddiebear[Keyword] Passing output '' to Run Script
[17:02:13.167] ERROR: Freddiebear[Run Script] Sat Oct 5 17:02:12 +08 2024 freddiebear.arm64.gz icon.png info.plist prefs.plist downloading ver=1.9.2 arch=arm64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     22      0 --:--:-- --:--:-- --:--:--    22
uncompressing
gzip: freddiebear.arm64.gz: not in gzip format
[17:02:13.176] Freddiebear[Run Script] Processing complete
[17:02:13.176] Freddiebear[Run Script] Passing output 'error
' to Conditional
[17:02:13.177] Freddiebear[Conditional] Processing complete
[17:02:13.177] Freddiebear[Conditional] Passing output 'error
' to Post Notification
```

**Comment by mnadel** [comment]
You mind sending the output of the following commands?

```
ls -l freddiebear.arm64.gz
file freddiebear.arm64.gz
```

And if it's not a binary file: `cat freddiebear.arm64.gz | head -50`
